// Code generated by genvanillatrades from Mojang 1.21.4 VillagerTrades; DO NOT EDIT.
package handler

import corentity "GoCraft/core/entity"

var vanillaVillagerTradeCatalog = map[corentity.VillagerProfession]map[int32][]tradeOffer{
	corentity.VillagerProfessionArmorer: {
		1: {
			{input1: tradeItem{"minecraft:coal", 15}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 7}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:iron_leggings", 1}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.2},
		},
		2: {
			{input1: tradeItem{"minecraft:iron_ingot", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 36}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:bell", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.2},
		},
		3: {
			{input1: tradeItem{"minecraft:lava_bucket", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:diamond", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:emerald", 14}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_leggings", 1}, maxUses: 3, xpPerTrade: 15, tier: 3, priceMultiplier: 0.2},
			{input1: tradeItem{"minecraft:emerald", 8}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_boots", 1}, maxUses: 3, xpPerTrade: 15, tier: 3, priceMultiplier: 0.2},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 8}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_helmet", 1}, maxUses: 3, xpPerTrade: 30, tier: 4, priceMultiplier: 0.2},
			{input1: tradeItem{"minecraft:emerald", 16}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_chestplate", 1}, maxUses: 3, xpPerTrade: 30, tier: 4, priceMultiplier: 0.2},
		},
	},
	corentity.VillagerProfessionButcher: {
		1: {
			{input1: tradeItem{"minecraft:chicken", 14}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:porkchop", 7}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:coal", 15}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:cooked_porkchop", 5}, maxUses: 16, xpPerTrade: 5, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:mutton", 7}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:beef", 10}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:dried_kelp_block", 10}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:sweet_berries", 10}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionCartographer: {
		1: {
			{input1: tradeItem{"minecraft:paper", 24}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 7}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:map", 1}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:glass_pane", 11}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 13}, input2: tradeItem{"minecraft:compass", 1}, output: tradeItem{"minecraft:filled_map", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.2},
		},
		3: {
			{input1: tradeItem{"minecraft:compass", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 14}, input2: tradeItem{"minecraft:compass", 1}, output: tradeItem{"minecraft:filled_map", 1}, maxUses: 12, xpPerTrade: 10, tier: 2, priceMultiplier: 0.2},
		},
		4: {
			{input1: tradeItem{"minecraft:emerald", 7}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:item_frame", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:white_banner", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 8}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:globe_banner_pattern", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionCleric: {
		1: {
			{input1: tradeItem{"minecraft:rotten_flesh", 32}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:redstone", 2}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:gold_ingot", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:lapis_lazuli", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:rabbit_foot", 2}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:glowstone", 1}, maxUses: 12, xpPerTrade: 10, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:turtle_scute", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:glass_bottle", 9}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:nether_wart", 22}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:experience_bottle", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionFarmer: {
		1: {
			{input1: tradeItem{"minecraft:wheat", 20}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:potato", 26}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:pumpkin", 6}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:pumpkin_pie", 4}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:cookie", 18}, maxUses: 12, xpPerTrade: 10, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:melon", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:cake", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:suspicious_stew", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:golden_carrot", 3}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:glistering_melon_slice", 3}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionFisherman: {
		1: {
			{input1: tradeItem{"minecraft:string", 20}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:coal", 10}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:cod", 15}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"minecraft:salmon", 6}, output: tradeItem{"minecraft:cooked_salmon", 6}, maxUses: 16, xpPerTrade: 5, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:salmon", 13}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:fishing_rod", 1}, maxUses: 3, xpPerTrade: 10, tier: 2, priceMultiplier: 0.2},
		},
		4: {
			{input1: tradeItem{"minecraft:tropical_fish", 6}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:pufferfish", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:oak_boat", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionFletcher: {
		1: {
			{input1: tradeItem{"minecraft:stick", 32}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:arrow", 16}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:flint", 26}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 2}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:bow", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:string", 14}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:crossbow", 1}, maxUses: 12, xpPerTrade: 10, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:feather", 24}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 2}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:bow", 1}, maxUses: 3, xpPerTrade: 15, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:tripwire_hook", 8}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:crossbow", 1}, maxUses: 3, xpPerTrade: 15, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionLeatherworker: {
		1: {
			{input1: tradeItem{"minecraft:leather", 6}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:leather_leggings", 1}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.2},
		},
		2: {
			{input1: tradeItem{"minecraft:flint", 26}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 5}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:leather_helmet", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.2},
		},
		3: {
			{input1: tradeItem{"minecraft:rabbit_hide", 9}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 7}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:leather_chestplate", 1}, maxUses: 12, xpPerTrade: 1, tier: 2, priceMultiplier: 0.2},
		},
		4: {
			{input1: tradeItem{"minecraft:turtle_scute", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 6}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:leather_horse_armor", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.2},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 6}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:saddle", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.2},
			{input1: tradeItem{"minecraft:emerald", 5}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:leather_helmet", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.2},
		},
	},
	corentity.VillagerProfessionLibrarian: {
		1: {
			{input1: tradeItem{"minecraft:paper", 24}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 10}, input2: tradeItem{"minecraft:book", 1}, output: tradeItem{"minecraft:enchanted_book", 1}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.2},
		},
		2: {
			{input1: tradeItem{"minecraft:book", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 10}, input2: tradeItem{"minecraft:book", 1}, output: tradeItem{"minecraft:enchanted_book", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.2},
		},
		3: {
			{input1: tradeItem{"minecraft:ink_sac", 5}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 10}, input2: tradeItem{"minecraft:book", 1}, output: tradeItem{"minecraft:enchanted_book", 1}, maxUses: 12, xpPerTrade: 10, tier: 2, priceMultiplier: 0.2},
		},
		4: {
			{input1: tradeItem{"minecraft:writable_book", 2}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 10}, input2: tradeItem{"minecraft:book", 1}, output: tradeItem{"minecraft:enchanted_book", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.2},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 20}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:name_tag", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionMason: {
		1: {
			{input1: tradeItem{"minecraft:clay_ball", 10}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:brick", 10}, maxUses: 16, xpPerTrade: 1, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:stone", 20}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:chiseled_stone_bricks", 4}, maxUses: 16, xpPerTrade: 5, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:granite", 16}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:andesite", 16}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:quartz", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:orange_terracotta", 1}, maxUses: 12, xpPerTrade: 15, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:quartz_pillar", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:quartz_block", 1}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionShepherd: {
		1: {
			{input1: tradeItem{"minecraft:white_wool", 18}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:brown_wool", 18}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
		},
		2: {
			{input1: tradeItem{"minecraft:white_dye", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:gray_dye", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
		},
		3: {
			{input1: tradeItem{"minecraft:yellow_dye", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:light_gray_dye", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:brown_dye", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:purple_dye", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 2}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:painting", 3}, maxUses: 12, xpPerTrade: 30, tier: 4, priceMultiplier: 0.05},
		},
	},
	corentity.VillagerProfessionToolsmith: {
		1: {
			{input1: tradeItem{"minecraft:coal", 15}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:stone_axe", 1}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.2},
		},
		2: {
			{input1: tradeItem{"minecraft:iron_ingot", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 36}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:bell", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.2},
		},
		3: {
			{input1: tradeItem{"minecraft:flint", 30}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:iron_axe", 1}, maxUses: 3, xpPerTrade: 10, tier: 2, priceMultiplier: 0.2},
		},
		4: {
			{input1: tradeItem{"minecraft:diamond", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_axe", 1}, maxUses: 3, xpPerTrade: 15, tier: 3, priceMultiplier: 0.2},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 13}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_pickaxe", 1}, maxUses: 3, xpPerTrade: 30, tier: 4, priceMultiplier: 0.2},
		},
	},
	corentity.VillagerProfessionWeaponsmith: {
		1: {
			{input1: tradeItem{"minecraft:coal", 15}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 16, xpPerTrade: 2, tier: 0, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 3}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:iron_axe", 1}, maxUses: 12, xpPerTrade: 1, tier: 0, priceMultiplier: 0.2},
		},
		2: {
			{input1: tradeItem{"minecraft:iron_ingot", 4}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 10, tier: 1, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 36}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:bell", 1}, maxUses: 12, xpPerTrade: 5, tier: 1, priceMultiplier: 0.2},
		},
		3: {
			{input1: tradeItem{"minecraft:flint", 24}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 20, tier: 2, priceMultiplier: 0.05},
		},
		4: {
			{input1: tradeItem{"minecraft:diamond", 1}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:emerald", 1}, maxUses: 12, xpPerTrade: 30, tier: 3, priceMultiplier: 0.05},
			{input1: tradeItem{"minecraft:emerald", 12}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_axe", 1}, maxUses: 3, xpPerTrade: 15, tier: 3, priceMultiplier: 0.2},
		},
		5: {
			{input1: tradeItem{"minecraft:emerald", 8}, input2: tradeItem{"", 0}, output: tradeItem{"minecraft:diamond_sword", 1}, maxUses: 3, xpPerTrade: 30, tier: 4, priceMultiplier: 0.2},
		},
	},
}
