// Command genpumpkinspawns converts Pumpkin's generated biome spawn tables
// into the compact Go data used by GoCraft's natural spawner.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var (
	biomePattern  = regexp.MustCompile(`(?s)pub const [A-Z0-9_]+: Biome = Biome \{.*?registry_id: "([^"]+)".*?creature_spawn_probability: ([0-9.]+)f32,\s*spawners: SpawnGroups \{(.*?)\n\s*\},\s*spawn_costs:`)
	spawnPattern  = regexp.MustCompile(`(?s)Spawner \{\s*r#type: "([^"]+)",\s*min_count: (-?[0-9]+)i32,\s*max_count: (-?[0-9]+)i32,\s*\}`)
	entityPattern = regexp.MustCompile(`(?s)pub const [A-Z0-9_]+: EntityType = EntityType \{(.*?)\n\s*resource_name: "([^"]+)",\s*\};`)
)

var categories = []string{
	"monster",
	"ambient",
	"axolotls",
	"creature",
	"misc",
	"underground_water_creature",
	"water_ambient",
	"water_creature",
}

type spawn struct {
	entity             string
	minCount, maxCount int
}

func main() {
	source := flag.String("source", "", "path to Pumpkin's generated biome.rs")
	entitySource := flag.String("entity-source", "", "path to Pumpkin's generated entity_type.rs")
	output := flag.String("output", "server/natural_spawn_data_generated.go", "generated Go output")
	experienceOutput := flag.String("experience-output", "server/entity_experience_data_generated.go", "generated entity XP output")
	flag.Parse()
	if *source == "" || *entitySource == "" {
		fmt.Fprintln(os.Stderr, "-source and -entity-source are required")
		os.Exit(2)
	}

	data, err := os.ReadFile(*source)
	if err != nil {
		fatal(err)
	}
	matches := biomePattern.FindAllSubmatch(data, -1)
	if len(matches) == 0 {
		fatal(fmt.Errorf("no Pumpkin biome definitions found in %s", *source))
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by internal/cmd/genpumpkinspawns from Pumpkin biome.rs; DO NOT EDIT.\n")
	out.WriteString("package server\n\n")
	out.WriteString("var pumpkinBiomeSpawns = map[string]pumpkinBiomeSpawnSettings{\n")
	for _, match := range matches {
		name, probability, body := string(match[1]), string(match[2]), string(match[3])
		fmt.Fprintf(&out, "\t%q: {creatureProbability: %s, groups: map[mobCategory][]pumpkinSpawnEntry{\n", "minecraft:"+name, probability)
		for i, category := range categories {
			section, ok := categorySection(body, category, nextCategory(i))
			if !ok {
				fatal(fmt.Errorf("biome %s has no %s spawn section", name, category))
			}
			entries := parseSpawns(section)
			if len(entries) == 0 {
				continue
			}
			fmt.Fprintf(&out, "\t\t%s: {\n", goCategory(category))
			for _, entry := range entries {
				fmt.Fprintf(&out, "\t\t\t{entityType: %q, minCount: %d, maxCount: %d},\n", entry.entity, entry.minCount, entry.maxCount)
			}
			out.WriteString("\t\t},\n")
		}
		out.WriteString("\t}},\n")
	}
	out.WriteString("}\n")

	entityData, err := os.ReadFile(*entitySource)
	if err != nil {
		fatal(err)
	}
	entityMatches := entityPattern.FindAllSubmatch(entityData, -1)
	if len(entityMatches) == 0 {
		fatal(fmt.Errorf("no Pumpkin entity definitions found in %s", *entitySource))
	}
	out.WriteString("\nvar pumpkinEntitySpawnSettingsByType = map[string]pumpkinEntitySpawnSettings{\n")
	for _, match := range entityMatches {
		body, name := string(match[1]), "minecraft:"+string(match[2])
		if field(body, `mob:\s*(true|false),`) != "true" {
			continue
		}
		category := field(body, `category: &MobCategory::([A-Z_]+),`)
		location := field(body, `location: SpawnLocation::([A-Za-z]+),`)
		if category == "" || location == "" {
			fatal(fmt.Errorf("entity %s is missing category or spawn location", name))
		}
		limit := field(body, `limit_per_chunk:\s*(-?[0-9]+)i32,`)
		if limit == "" {
			limit = "4"
		}
		summonable := field(body, `summonable:\s*(true|false),`)
		canSpawnFar := field(body, `can_spawn_far_from_player:\s*(true|false),`)
		movementSpeed := attribute(body, "MOVEMENT_SPEED", "0")
		followRange := attribute(body, "FOLLOW_RANGE", "16")
		attackDamage := attribute(body, "ATTACK_DAMAGE", "0")
		fmt.Fprintf(&out, "\t%q: {category: %s, location: spawnLocation%s, limitPerChunk: %s, summonable: %s, canSpawnFarFromPlayer: %s, movementSpeed: %s, followRange: %s, attackDamage: %s},\n",
			name, goCategory(strings.ToLower(category)), location, limit, summonable, canSpawnFar, movementSpeed, followRange, attackDamage)
	}
	out.WriteString("}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fatal(fmt.Errorf("format generated source: %w\n%s", err, out.String()))
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatal(err)
	}

	var experience bytes.Buffer
	experience.WriteString("// Code generated by internal/cmd/genpumpkinspawns from Pumpkin entity_type.rs; DO NOT EDIT.\npackage server\n\n")
	experience.WriteString("var pumpkinExperienceRewardByType = map[string]int32{\n")
	for _, match := range entityMatches {
		body, name := string(match[1]), "minecraft:"+string(match[2])
		reward := field(body, `experience_reward:\s*([0-9]+)u32,`)
		if reward != "" && reward != "0" {
			fmt.Fprintf(&experience, "\t%q: %s,\n", name, reward)
		}
	}
	experience.WriteString("}\n")
	experienceFormatted, err := format.Source(experience.Bytes())
	if err != nil {
		fatal(fmt.Errorf("format generated experience source: %w", err))
	}
	if err := os.WriteFile(*experienceOutput, experienceFormatted, 0o644); err != nil {
		fatal(err)
	}
}

func field(body, pattern string) string {
	match := regexp.MustCompile(pattern).FindStringSubmatch(body)
	if len(match) != 2 {
		return ""
	}
	return match[1]
}

func attribute(body, name, fallback string) string {
	value := field(body, `\(Attributes::`+name+`,\s*([0-9.Ee+-]+)f64\)`)
	if value == "" {
		return fallback
	}
	return value
}

func categorySection(body, category, next string) (string, bool) {
	// Include the field indentation in the marker. Without this boundary,
	// "water_creature" also matches the suffix of
	// "underground_water_creature", merging three aquatic categories and
	// allowing the runtime spawner to bypass their individual caps.
	startMarker := "\n            " + category + ": &["
	start := strings.Index(body, startMarker)
	if start < 0 {
		return "", false
	}
	start += len(startMarker)
	if next == "" {
		end := strings.LastIndex(body[start:], "]")
		if end < 0 {
			return "", false
		}
		return body[start : start+end], true
	}
	endMarker := "\n            " + next + ": &["
	end := strings.Index(body[start:], endMarker)
	if end < 0 {
		return "", false
	}
	return body[start : start+end], true
}

func nextCategory(index int) string {
	if index+1 >= len(categories) {
		return ""
	}
	return categories[index+1]
}

func parseSpawns(section string) []spawn {
	matches := spawnPattern.FindAllStringSubmatch(section, -1)
	out := make([]spawn, 0, len(matches))
	for _, match := range matches {
		minCount, err := strconv.Atoi(match[2])
		if err != nil {
			fatal(err)
		}
		maxCount, err := strconv.Atoi(match[3])
		if err != nil {
			fatal(err)
		}
		out = append(out, spawn{entity: match[1], minCount: minCount, maxCount: maxCount})
	}
	return out
}

func goCategory(category string) string {
	parts := strings.Split(category, "_")
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return "mobCategory" + strings.Join(parts, "")
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
