// Command genpumpkinregistry converts Pumpkin's Bedrock runtime item table
// into Go source and copies its compressed item-component NBT into the package
// that advertises both during StartGame.
package genpumpkinregistry

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"

	"github.com/spf13/viper"
)

type runtimeItemState struct {
	Name           string `json:"name"`
	ID             int32  `json:"id"`
	Version        int32  `json:"version"`
	ComponentBased bool   `json:"componentBased"`
}

func Generate() error {
	input := viper.GetString("input")
	components := viper.GetString("components")
	output := viper.GetString("output")
	componentOutput := viper.GetString("component-output")

	if input == "" || components == "" {
		panic("-input and -components are required")
	}

	raw, err := os.ReadFile(input)
	if err != nil {
		panic(err)
	}

	var states []runtimeItemState
	if err := json.Unmarshal(raw, &states); err != nil {
		panic(err)
	}

	seenNames := make(map[string]struct{}, len(states))
	seenIDs := make(map[int32]struct{}, len(states))
	for index, state := range states {
		if state.Name == "" || state.ID < -32768 || state.ID > 32767 {
			panic(fmt.Sprintf("invalid item %d: %#v", index, state))
		}

		if _, exists := seenNames[state.Name]; exists {
			panic(fmt.Sprintf("duplicate item name %q", state.Name))
		}

		if _, exists := seenIDs[state.ID]; exists {
			panic(fmt.Sprintf("duplicate item runtime ID %d", state.ID))
		}
		seenNames[state.Name] = struct{}{}
		seenIDs[state.ID] = struct{}{}
	}

	var generated bytes.Buffer
	generated.WriteString("// Code generated by genpumpkinregistry; DO NOT EDIT.\n\npackage bedrock\n\n")
	generated.WriteString("type pumpkinItemRegistryData struct {\n\tname string\n\truntimeID int16\n\tversion int32\n\tcomponentBased bool\n}\n\n")
	generated.WriteString("var pumpkinItemRegistryDataEntries = []pumpkinItemRegistryData{\n")
	for _, state := range states {
		fmt.Fprintf(&generated, "\t{name: %s, runtimeID: %d, version: %d, componentBased: %t},\n",
			strconv.Quote(state.Name), state.ID, state.Version, state.ComponentBased)
	}

	generated.WriteString("}\n")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		panic(err)
	}

	if err := os.MkdirAll(filepath.Dir(output), 0o755); err != nil {
		panic(err)
	}

	if err := os.WriteFile(output, formatted, 0o644); err != nil {
		panic(err)
	}

	componentData, err := os.ReadFile(components)
	if err != nil {
		panic(err)
	}

	if len(componentData) < 2 || componentData[0] != 0x1f || componentData[1] != 0x8b {
		panic("item component asset is not gzip-compressed NBT")
	}

	if err := os.MkdirAll(filepath.Dir(componentOutput), 0o755); err != nil {
		panic(err)
	}

	if err := os.WriteFile(componentOutput, componentData, 0o644); err != nil {
		panic(err)
	}

	return nil
}
