// Code generated by protoc-gen-gocraft. DO NOT EDIT.
//
// Source: abi/v1/events.proto

package plugin

import (
	abi "GoCraft/abi/v1"
	"GoCraft/core/player"
	"GoCraft/core/spatial"
	coreworld "GoCraft/core/world"
)

// Event types, as a manifest spells them.
const (
	// Cancellable, blocks the tick, defaults to allow. Introduced in ABI 1.
	EventBlockBreak = "block.break"
	// Observational, never cancelled. Introduced in ABI 1.
	EventPlayerJoin = "player.join"
)

// EmitBlockBreak publishes block.break to every subscriber, in the same shape whatever
// edition the player is on and whatever runtime the plugin uses.
//
// It blocks the tick under the budget shared by every subscriber, and reports
// whether the action may proceed. A false return means a plugin refused it.
func (b *Bus) EmitBlockBreak(playerRef *player.Player, pos spatial.BlockPos, block coreworld.Block, tool string) bool {
	if !b.hasSubscribers(EventBlockBreak) {
		return true
	}
	event := &abi.Event{
		Type:      EventBlockBreak,
		OnFailure: abi.FailureAllow,
		Fields: []abi.Value{
			playerReference(playerRef),
			positionValue(pos),
			blockValue(block),
			abi.String(tool),
			b.injectedPermissions(EventBlockBreak, playerRef),
		},
	}
	return b.EmitCancellable(event)
}

// EmitPlayerJoin publishes player.join to every subscriber, in the same shape whatever
// edition the player is on and whatever runtime the plugin uses.
//
// Observational: the tick does not wait, and nothing a subscriber does can
// prevent what already happened.
func (b *Bus) EmitPlayerJoin(playerRef *player.Player) {
	if !b.hasSubscribers(EventPlayerJoin) {
		return
	}
	event := &abi.Event{
		Type:      EventPlayerJoin,
		OnFailure: abi.FailureAllow,
		Fields: []abi.Value{
			playerReference(playerRef),
			b.injectedPermissions(EventPlayerJoin, playerRef),
		},
	}
	b.EmitObservational(event)
}

// EmitPlayerJoinTo replays player.join to named plugins only.
//
// For a runtime that died and was brought back: its plugins missed what
// happened while they were down, and the ones that stayed up did not.
func (b *Bus) EmitPlayerJoinTo(plugins []string, playerRef *player.Player) {
	if len(plugins) == 0 {
		return
	}
	event := &abi.Event{
		Type:      EventPlayerJoin,
		OnFailure: abi.FailureAllow,
		Fields: []abi.Value{
			playerReference(playerRef),
			b.injectedPermissions(EventPlayerJoin, playerRef),
		},
	}
	b.EmitObservationalTo(event, plugins)
}
