// Command genpumpkinitems converts Pumpkin's generated Rust item mappings
// into the compact Go table used by the Bedrock bridge.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type itemDefinition struct {
	registryKey string
	runtimeID   int64
}

type itemMapping struct {
	javaName, bedrockName string
	runtimeID             int64
	metadata, blockState  uint64
}

var (
	constantPattern = regexp.MustCompile(`(?s)pub const ([A-Z0-9_]+)\s*: Self = Self \{\s*id\s*:\s*(-?[0-9]+)\s*,\s*registry_key\s*:\s*"([^"]+)"\s*,`)
	mappingPattern  = regexp.MustCompile(`(?s)pub const [A-Z0-9_]+: Self = Self \{\s*java_item:\s*&Item::([A-Z0-9_]+),\s*bedrock_item:\s*&BedrockItem::([A-Z0-9_]+),\s*bedrock_data:\s*([0-9]+),\s*bedrock_block_state:\s*([0-9]+),\s*\};`)
)

func main() {
	source := flag.String("source", "", "Pumpkin crates/pumpkin-data/src/generated/item.rs")
	output := flag.String("output", "bedrock/item_mappings_generated.go", "generated Go output")
	flag.Parse()
	if *source == "" {
		fatalf("-source is required")
	}
	raw, err := os.ReadFile(*source)
	if err != nil {
		fatalf("read source: %v", err)
	}
	text := string(raw)
	itemStart := strings.Index(text, "impl Item {")
	bedrockStart := strings.Index(text, "impl BedrockItem {")
	mappingStart := strings.Index(text, "impl JavaToBedrockItemMapping {")
	if itemStart < 0 || bedrockStart <= itemStart || mappingStart <= bedrockStart {
		fatalf("could not locate generated Rust mapping sections")
	}

	javaItems := parseConstants(text[itemStart:bedrockStart])
	bedrockItems := parseConstants(text[bedrockStart:mappingStart])
	mappings := make([]itemMapping, 0, len(javaItems))
	for _, match := range mappingPattern.FindAllStringSubmatch(text[mappingStart:], -1) {
		javaItem, javaOK := javaItems[match[1]]
		bedrockItem, bedrockOK := bedrockItems[match[2]]
		if !javaOK {
			fatalf("mapping %s references a missing Java item constant", match[1])
		}
		if !bedrockOK {
			fatalf("mapping %s references missing Bedrock item constant %s", match[1], match[2])
		}
		metadata, metadataErr := strconv.ParseUint(match[3], 10, 32)
		blockState, blockStateErr := strconv.ParseUint(match[4], 10, 32)
		if metadataErr != nil || blockStateErr != nil {
			fatalf("invalid mapping values for %s", match[1])
		}
		mappings = append(mappings, itemMapping{
			javaName:    "minecraft:" + javaItem.registryKey,
			bedrockName: bedrockItem.registryKey,
			runtimeID:   bedrockItem.runtimeID,
			metadata:    metadata,
			blockState:  blockState,
		})
	}
	// Bedrock renamed the Java 1.21.4 chain item to iron_chain. Pumpkin's
	// current generated table naturally targets the renamed Java item, so keep
	// the old Java identifier as a compatibility alias for 1.21.4 recipes.
	for _, mapping := range mappings {
		if mapping.javaName == "minecraft:iron_chain" {
			mapping.javaName = "minecraft:chain"
			mappings = append(mappings, mapping)
			break
		}
	}
	sort.Slice(mappings, func(i, j int) bool { return mappings[i].javaName < mappings[j].javaName })

	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by internal/cmd/genpumpkinitems; DO NOT EDIT.")
	fmt.Fprintln(&generated, "// Source: Pumpkin's generated Java-to-Bedrock item mappings (GPL-3.0).")
	fmt.Fprintln(&generated, "package bedrock")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "type bedrockItemMapping struct {")
	fmt.Fprintln(&generated, "name string")
	fmt.Fprintln(&generated, "runtimeID int32")
	fmt.Fprintln(&generated, "metadata uint32")
	fmt.Fprintln(&generated, "blockRuntimeID int32")
	fmt.Fprintln(&generated, "}")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "var javaToBedrockItemMappings = map[string]bedrockItemMapping{")
	for _, mapping := range mappings {
		fmt.Fprintf(&generated, "%q: {name: %q, runtimeID: %d, metadata: %d, blockRuntimeID: %d},\n",
			mapping.javaName, mapping.bedrockName, mapping.runtimeID, mapping.metadata, mapping.blockState)
	}
	fmt.Fprintln(&generated, "}")

	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatalf("write output: %v", err)
	}
	fmt.Printf("generated %d Java-to-Bedrock item mappings in %s\n", len(mappings), *output)
}

func parseConstants(section string) map[string]itemDefinition {
	items := make(map[string]itemDefinition)
	for _, match := range constantPattern.FindAllStringSubmatch(section, -1) {
		runtimeID, err := strconv.ParseInt(match[2], 10, 32)
		if err != nil {
			fatalf("invalid runtime ID for %s: %v", match[1], err)
		}
		items[match[1]] = itemDefinition{registryKey: match[3], runtimeID: runtimeID}
	}
	return items
}

func fatalf(format string, values ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", values...)
	os.Exit(1)
}
