// Code generated by internal/cmd/genpumpkinspawns from Pumpkin biome.rs; DO NOT EDIT.
package server

var pumpkinBiomeSpawns = map[string]pumpkinBiomeSpawnSettings{
	"minecraft:badlands": {creatureProbability: 0.03, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:armadillo", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:bamboo_jungle": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:ocelot", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:parrot", minCount: 1, maxCount: 2},
			{entityType: "minecraft:panda", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:basalt_deltas": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:ghast", minCount: 1, maxCount: 1},
			{entityType: "minecraft:magma_cube", minCount: 2, maxCount: 5},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:strider", minCount: 1, maxCount: 2},
		},
	}},
	"minecraft:beach": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:turtle", minCount: 2, maxCount: 5},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:birch_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:cherry_grove": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:pig", minCount: 1, maxCount: 2},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 6},
			{entityType: "minecraft:sheep", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:cold_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:cod", minCount: 3, maxCount: 6},
			{entityType: "minecraft:salmon", minCount: 1, maxCount: 5},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:crimson_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:zombified_piglin", minCount: 2, maxCount: 4},
			{entityType: "minecraft:hoglin", minCount: 3, maxCount: 4},
			{entityType: "minecraft:piglin", minCount: 3, maxCount: 4},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:strider", minCount: 1, maxCount: 2},
		},
	}},
	"minecraft:dark_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:deep_cold_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:cod", minCount: 3, maxCount: 6},
			{entityType: "minecraft:salmon", minCount: 1, maxCount: 5},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:deep_dark": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{}},
	"minecraft:deep_frozen_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:polar_bear", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:salmon", minCount: 1, maxCount: 5},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:deep_lukewarm_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:cod", minCount: 3, maxCount: 6},
			{entityType: "minecraft:pufferfish", minCount: 1, maxCount: 3},
			{entityType: "minecraft:tropical_fish", minCount: 8, maxCount: 8},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:dolphin", minCount: 1, maxCount: 2},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:deep_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:cod", minCount: 3, maxCount: 6},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:dolphin", minCount: 1, maxCount: 2},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:desert": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:husk", minCount: 4, maxCount: 4},
			{entityType: "minecraft:parched", minCount: 4, maxCount: 4},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:camel", minCount: 1, maxCount: 1},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:dripstone_caves": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 4, maxCount: 4},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:end_barrens": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
	}},
	"minecraft:end_highlands": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
	}},
	"minecraft:end_midlands": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
	}},
	"minecraft:eroded_badlands": {creatureProbability: 0.03, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:armadillo", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:flower_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:frozen_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:polar_bear", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:salmon", minCount: 1, maxCount: 5},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:frozen_peaks": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:goat", minCount: 1, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:frozen_river": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:salmon", minCount: 1, maxCount: 5},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
		},
	}},
	"minecraft:grove": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:wolf", minCount: 1, maxCount: 1},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:fox", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:ice_spikes": {creatureProbability: 0.07, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:stray", minCount: 4, maxCount: 4},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:polar_bear", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:jagged_peaks": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:goat", minCount: 1, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:jungle": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:ocelot", minCount: 1, maxCount: 3},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:parrot", minCount: 1, maxCount: 2},
			{entityType: "minecraft:panda", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:lukewarm_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:cod", minCount: 3, maxCount: 6},
			{entityType: "minecraft:pufferfish", minCount: 1, maxCount: 3},
			{entityType: "minecraft:tropical_fish", minCount: 8, maxCount: 8},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 2},
			{entityType: "minecraft:dolphin", minCount: 1, maxCount: 2},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:lush_caves": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryAxolotls: {
			{entityType: "minecraft:axolotl", minCount: 4, maxCount: 6},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:tropical_fish", minCount: 8, maxCount: 8},
		},
	}},
	"minecraft:mangrove_swamp": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:slime", minCount: 1, maxCount: 1},
			{entityType: "minecraft:bogged", minCount: 4, maxCount: 4},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:frog", minCount: 2, maxCount: 5},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:tropical_fish", minCount: 8, maxCount: 8},
		},
	}},
	"minecraft:meadow": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:donkey", minCount: 1, maxCount: 2},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 6},
			{entityType: "minecraft:sheep", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:mushroom_fields": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:mooshroom", minCount: 4, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:nether_wastes": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:ghast", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombified_piglin", minCount: 4, maxCount: 4},
			{entityType: "minecraft:magma_cube", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
			{entityType: "minecraft:piglin", minCount: 4, maxCount: 4},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:strider", minCount: 1, maxCount: 2},
		},
	}},
	"minecraft:ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:cod", minCount: 3, maxCount: 6},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
			{entityType: "minecraft:dolphin", minCount: 1, maxCount: 2},
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
		},
	}},
	"minecraft:old_growth_birch_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:old_growth_pine_taiga": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 4},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:fox", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:old_growth_spruce_taiga": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 4},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:fox", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:pale_garden": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:plains": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_horse", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:horse", minCount: 2, maxCount: 6},
			{entityType: "minecraft:donkey", minCount: 1, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:river": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:salmon", minCount: 1, maxCount: 5},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:squid", minCount: 1, maxCount: 4},
		},
	}},
	"minecraft:savanna": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_horse", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:horse", minCount: 2, maxCount: 6},
			{entityType: "minecraft:donkey", minCount: 1, maxCount: 1},
			{entityType: "minecraft:armadillo", minCount: 2, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:savanna_plateau": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_horse", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:horse", minCount: 2, maxCount: 6},
			{entityType: "minecraft:donkey", minCount: 1, maxCount: 1},
			{entityType: "minecraft:armadillo", minCount: 2, maxCount: 3},
			{entityType: "minecraft:llama", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:small_end_islands": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
	}},
	"minecraft:snowy_beach": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:snowy_plains": {creatureProbability: 0.07, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_horse", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:stray", minCount: 4, maxCount: 4},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:polar_bear", minCount: 1, maxCount: 2},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:snowy_slopes": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:goat", minCount: 1, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:snowy_taiga": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 4},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:fox", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:soul_sand_valley": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:skeleton", minCount: 5, maxCount: 5},
			{entityType: "minecraft:ghast", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:strider", minCount: 1, maxCount: 2},
		},
	}},
	"minecraft:sparse_jungle": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:stony_peaks": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:stony_shore": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:sulfur_caves": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:sulfur_cube", minCount: 2, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 2, maxCount: 2},
			{entityType: "minecraft:skeleton", minCount: 2, maxCount: 2},
			{entityType: "minecraft:slime", minCount: 1, maxCount: 1},
			{entityType: "minecraft:cave_spider", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie", minCount: 2, maxCount: 2},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 1},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
	}},
	"minecraft:sunflower_plains": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_horse", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:horse", minCount: 2, maxCount: 6},
			{entityType: "minecraft:donkey", minCount: 1, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:swamp": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
			{entityType: "minecraft:slime", minCount: 1, maxCount: 1},
			{entityType: "minecraft:bogged", minCount: 4, maxCount: 4},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:frog", minCount: 2, maxCount: 5},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:taiga": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 4},
			{entityType: "minecraft:rabbit", minCount: 2, maxCount: 3},
			{entityType: "minecraft:fox", minCount: 2, maxCount: 4},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:the_end": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
	}},
	"minecraft:the_void": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{}},
	"minecraft:warm_ocean": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:drowned", minCount: 1, maxCount: 1},
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
		mobCategoryWaterAmbient: {
			{entityType: "minecraft:pufferfish", minCount: 1, maxCount: 3},
			{entityType: "minecraft:tropical_fish", minCount: 8, maxCount: 8},
		},
		mobCategoryWaterCreature: {
			{entityType: "minecraft:nautilus", minCount: 1, maxCount: 1},
			{entityType: "minecraft:squid", minCount: 4, maxCount: 4},
			{entityType: "minecraft:dolphin", minCount: 1, maxCount: 2},
		},
	}},
	"minecraft:warped_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:enderman", minCount: 4, maxCount: 4},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:strider", minCount: 1, maxCount: 2},
		},
	}},
	"minecraft:windswept_forest": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:llama", minCount: 4, maxCount: 6},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:windswept_gravelly_hills": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:llama", minCount: 4, maxCount: 6},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:windswept_hills": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:llama", minCount: 4, maxCount: 6},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:windswept_savanna": {creatureProbability: 0.1, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:zombie_horse", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:horse", minCount: 2, maxCount: 6},
			{entityType: "minecraft:donkey", minCount: 1, maxCount: 1},
			{entityType: "minecraft:armadillo", minCount: 2, maxCount: 3},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
	"minecraft:wooded_badlands": {creatureProbability: 0.04, groups: map[mobCategory][]pumpkinSpawnEntry{
		mobCategoryMonster: {
			{entityType: "minecraft:spider", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie", minCount: 4, maxCount: 4},
			{entityType: "minecraft:zombie_villager", minCount: 1, maxCount: 1},
			{entityType: "minecraft:skeleton", minCount: 4, maxCount: 4},
			{entityType: "minecraft:creeper", minCount: 4, maxCount: 4},
			{entityType: "minecraft:slime", minCount: 4, maxCount: 4},
			{entityType: "minecraft:enderman", minCount: 1, maxCount: 4},
			{entityType: "minecraft:witch", minCount: 1, maxCount: 1},
		},
		mobCategoryAmbient: {
			{entityType: "minecraft:bat", minCount: 8, maxCount: 8},
		},
		mobCategoryCreature: {
			{entityType: "minecraft:sheep", minCount: 4, maxCount: 4},
			{entityType: "minecraft:pig", minCount: 4, maxCount: 4},
			{entityType: "minecraft:chicken", minCount: 4, maxCount: 4},
			{entityType: "minecraft:cow", minCount: 4, maxCount: 4},
			{entityType: "minecraft:armadillo", minCount: 1, maxCount: 2},
			{entityType: "minecraft:wolf", minCount: 4, maxCount: 8},
		},
		mobCategoryUndergroundWaterCreature: {
			{entityType: "minecraft:glow_squid", minCount: 4, maxCount: 6},
		},
	}},
}

var pumpkinEntitySpawnSettingsByType = map[string]pumpkinEntitySpawnSettings{
	"minecraft:allay":            {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.10000000149011612, followRange: 16, attackDamage: 2},
	"minecraft:armadillo":        {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.14, followRange: 16, attackDamage: 0},
	"minecraft:axolotl":          {category: mobCategoryAxolotls, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 1, followRange: 16, attackDamage: 2},
	"minecraft:bat":              {category: mobCategoryAmbient, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:bee":              {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 2},
	"minecraft:blaze":            {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.2300000041723251, followRange: 48, attackDamage: 6},
	"minecraft:bogged":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:breeze":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.6299999952316284, followRange: 24, attackDamage: 3},
	"minecraft:camel":            {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.09000000357627869, followRange: 16, attackDamage: 0},
	"minecraft:camel_husk":       {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.09000000357627869, followRange: 16, attackDamage: 0},
	"minecraft:cat":              {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 3},
	"minecraft:cave_spider":      {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 2},
	"minecraft:chicken":          {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.25, followRange: 16, attackDamage: 0},
	"minecraft:cod":              {category: mobCategoryWaterAmbient, location: spawnLocationInWater, limitPerChunk: 8, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:copper_golem":     {category: mobCategoryMisc, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 0},
	"minecraft:cow":              {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 0},
	"minecraft:creaking":         {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.4000000059604645, followRange: 32, attackDamage: 3},
	"minecraft:creeper":          {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:dolphin":          {category: mobCategoryWaterCreature, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 1.2000000476837158, followRange: 16, attackDamage: 3},
	"minecraft:donkey":           {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.17499999701976776, followRange: 16, attackDamage: 0},
	"minecraft:drowned":          {category: mobCategoryMonster, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.2300000041723251, followRange: 35, attackDamage: 3},
	"minecraft:elder_guardian":   {category: mobCategoryMonster, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 8},
	"minecraft:ender_dragon":     {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:enderman":         {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 64, attackDamage: 7},
	"minecraft:endermite":        {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:evoker":           {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.5, followRange: 12, attackDamage: 2},
	"minecraft:fox":              {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.30000001192092896, followRange: 32, attackDamage: 2},
	"minecraft:frog":             {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 1, followRange: 16, attackDamage: 10},
	"minecraft:ghast":            {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 1, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 100, attackDamage: 0},
	"minecraft:giant":            {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.5, followRange: 16, attackDamage: 50},
	"minecraft:glow_squid":       {category: mobCategoryUndergroundWaterCreature, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:goat":             {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 2},
	"minecraft:guardian":         {category: mobCategoryMonster, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.5, followRange: 16, attackDamage: 6},
	"minecraft:happy_ghast":      {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 1, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.05, followRange: 16, attackDamage: 0},
	"minecraft:hoglin":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 6},
	"minecraft:horse":            {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.22499999403953552, followRange: 16, attackDamage: 0},
	"minecraft:husk":             {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.2300000041723251, followRange: 35, attackDamage: 3},
	"minecraft:illusioner":       {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.5, followRange: 18, attackDamage: 2},
	"minecraft:iron_golem":       {category: mobCategoryMisc, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.25, followRange: 16, attackDamage: 15},
	"minecraft:llama":            {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.17499999701976776, followRange: 16, attackDamage: 0},
	"minecraft:magma_cube":       {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 2},
	"minecraft:mooshroom":        {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 0},
	"minecraft:mule":             {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.17499999701976776, followRange: 16, attackDamage: 0},
	"minecraft:nautilus":         {category: mobCategoryWaterCreature, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 1, followRange: 16, attackDamage: 3},
	"minecraft:ocelot":           {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 3},
	"minecraft:panda":            {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.15000000596046448, followRange: 16, attackDamage: 6},
	"minecraft:parched":          {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:parrot":           {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 3},
	"minecraft:phantom":          {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 2},
	"minecraft:pig":              {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.25, followRange: 16, attackDamage: 0},
	"minecraft:piglin":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.3499999940395355, followRange: 16, attackDamage: 5},
	"minecraft:piglin_brute":     {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.3499999940395355, followRange: 12, attackDamage: 7},
	"minecraft:pillager":         {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 1, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.3499999940395355, followRange: 32, attackDamage: 5},
	"minecraft:polar_bear":       {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.25, followRange: 20, attackDamage: 6},
	"minecraft:pufferfish":       {category: mobCategoryWaterAmbient, location: spawnLocationInWater, limitPerChunk: 8, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:rabbit":           {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 3},
	"minecraft:ravager":          {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.3, followRange: 32, attackDamage: 12},
	"minecraft:salmon":           {category: mobCategoryWaterAmbient, location: spawnLocationInWater, limitPerChunk: 5, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:sheep":            {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.2300000041723251, followRange: 16, attackDamage: 0},
	"minecraft:shulker":          {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:silverfish":       {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 1},
	"minecraft:skeleton":         {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:skeleton_horse":   {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 0},
	"minecraft:slime":            {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 2},
	"minecraft:sniffer":          {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.10000000149011612, followRange: 16, attackDamage: 0},
	"minecraft:snow_golem":       {category: mobCategoryMisc, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.20000000298023224, followRange: 16, attackDamage: 0},
	"minecraft:spider":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 2},
	"minecraft:squid":            {category: mobCategoryWaterCreature, location: spawnLocationInWater, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:stray":            {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:strider":          {category: mobCategoryCreature, location: spawnLocationInLava, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.17499999701976776, followRange: 16, attackDamage: 0},
	"minecraft:sulfur_cube":      {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:tadpole":          {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 8, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 1, followRange: 16, attackDamage: 0},
	"minecraft:trader_llama":     {category: mobCategoryCreature, location: spawnLocationUnrestricted, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.17499999701976776, followRange: 16, attackDamage: 0},
	"minecraft:tropical_fish":    {category: mobCategoryWaterAmbient, location: spawnLocationInWater, limitPerChunk: 8, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:turtle":           {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.25, followRange: 16, attackDamage: 0},
	"minecraft:vex":              {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.7, followRange: 16, attackDamage: 4},
	"minecraft:villager":         {category: mobCategoryMisc, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.5, followRange: 16, attackDamage: 0},
	"minecraft:vindicator":       {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.3499999940395355, followRange: 12, attackDamage: 5},
	"minecraft:wandering_trader": {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.7, followRange: 16, attackDamage: 0},
	"minecraft:warden":           {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 24, attackDamage: 30},
	"minecraft:witch":            {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:wither":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.6000000238418579, followRange: 40, attackDamage: 2},
	"minecraft:wither_skeleton":  {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.25, followRange: 16, attackDamage: 2},
	"minecraft:wolf":             {category: mobCategoryCreature, location: spawnLocationOnGround, limitPerChunk: 8, summonable: true, canSpawnFarFromPlayer: true, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 4},
	"minecraft:zoglin":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.30000001192092896, followRange: 16, attackDamage: 6},
	"minecraft:zombie":           {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.2300000041723251, followRange: 35, attackDamage: 3},
	"minecraft:zombie_horse":     {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 6, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.22499999403953552, followRange: 16, attackDamage: 0},
	"minecraft:zombie_nautilus":  {category: mobCategoryMonster, location: spawnLocationUnrestricted, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 1.100000023841858, followRange: 16, attackDamage: 3},
	"minecraft:zombie_villager":  {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.2300000041723251, followRange: 35, attackDamage: 3},
	"minecraft:zombified_piglin": {category: mobCategoryMonster, location: spawnLocationOnGround, limitPerChunk: 4, summonable: true, canSpawnFarFromPlayer: false, movementSpeed: 0.2300000041723251, followRange: 35, attackDamage: 5},
}
