package main

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateGo writes the host side: one type constant and one typed emitter per
// event.
//
// It replaces what used to be hand-written. Keeping both would mean the Go
// payload and the Java accessors could disagree about what index 3 holds, and
// nothing would notice until a handler read the wrong field — which is the
// drift §01 exists to prevent.
//
// The emitters call hand-written vocabulary helpers rather than inlining the
// conversions, because those are the fifteen types where generated code would
// be mediocre.
func generateGo(plugin *protogen.Plugin, events []event) error {
	file := plugin.NewGeneratedFile("core/plugin/events.gen.go", "GoCraft/core/plugin")

	file.P("// Code generated by protoc-gen-gocraft. DO NOT EDIT.")
	file.P("//")
	file.P("// Source: abi/v1/events.proto")
	file.P()
	file.P("package plugin")
	file.P()
	file.P("import (")
	file.P("	abi \"GoCraft/abi/v1\"")
	for _, line := range imports(events) {
		file.P("	" + line)
	}
	file.P(")")
	file.P()

	file.P("// Event types, as a manifest spells them.")
	file.P("const (")
	for _, declared := range events {
		file.P(fmt.Sprintf("\t// %s. Introduced in ABI %d.", describe(declared), declared.Since))
		file.P(fmt.Sprintf("\t%s = %q", declared.ConstName(), declared.Type))
	}
	file.P(")")
	file.P()

	for _, declared := range events {
		if err := emitter(file, declared); err != nil {
			return err
		}
	}

	return nil
}

// imports lists the vocabulary packages this event set needs, sorted and
// deduplicated.
//
// Computed rather than fixed: a list written by hand breaks the day a schema
// drops its last BlockPos, and padding it with blank identifiers to stop that
// is worse than working it out.
func imports(events []event) []string {
	seen := make(map[string]struct{})
	var lines []string
	for _, declared := range events {
		for _, f := range declared.Fields {
			if f.Injected {
				continue
			}
			bound, err := bindingFor(f.Kind)
			if err != nil || bound.GoImport == "" {
				continue
			}
			if _, duplicate := seen[bound.GoImport]; duplicate {
				continue
			}
			seen[bound.GoImport] = struct{}{}
			lines = append(lines, bound.GoImport)
		}
	}
	sort.Strings(lines)
	return lines
}

func emitter(file *protogen.GeneratedFile, declared event) error {
	parameters := make([]string, 0, len(declared.Fields))
	values := make([]string, 0, len(declared.Fields))
	var actor string

	for _, f := range declared.Fields {
		if f.Injected {
			// The host resolves this rather than being handed it, which is
			// what lets a handler answer can() without a round trip.
			values = append(values, fmt.Sprintf("b.injectedPermissions(%s, %s)",
				declared.ConstName(), actorOr(actor)))
			continue
		}
		bound, err := bindingFor(f.Kind)
		if err != nil {
			return fmt.Errorf("%s.%s: %w", declared.Type, f.Name, err)
		}
		name := parameterName(f)
		parameters = append(parameters, name+" "+bound.GoType)
		values = append(values, fmt.Sprintf(bound.GoEncode, name))
		if f.Kind == "PlayerRef" && actor == "" {
			actor = name
		}
	}

	file.P(fmt.Sprintf("// %s publishes %s to every subscriber, in the same shape whatever",
		declared.EmitName(), declared.Type))
	file.P("// edition the player is on and whatever runtime the plugin uses.")
	if declared.Cancellable {
		file.P("//")
		file.P("// It blocks the tick under the budget shared by every subscriber, and reports")
		file.P("// whether the action may proceed. A false return means a plugin refused it.")
	} else {
		file.P("//")
		file.P("// Observational: the tick does not wait, and nothing a subscriber does can")
		file.P("// prevent what already happened.")
	}

	signature := fmt.Sprintf("func (b *Bus) %s(%s)", declared.EmitName(), strings.Join(parameters, ", "))
	if declared.Cancellable {
		signature += " bool"
	}
	file.P(signature + " {")

	// An event with no subscriber costs not one serialization. The bus would
	// reach the same answer, but only after building a payload nobody wants.
	if declared.Cancellable {
		file.P(fmt.Sprintf("\tif !b.hasSubscribers(%s) {", declared.ConstName()))
		file.P("\t\treturn true")
		file.P("\t}")
	} else {
		file.P(fmt.Sprintf("\tif !b.hasSubscribers(%s) {", declared.ConstName()))
		file.P("\t\treturn")
		file.P("\t}")
	}

	file.P("\tevent := &abi.Event{")
	file.P(fmt.Sprintf("\t\tType:      %s,", declared.ConstName()))
	file.P(fmt.Sprintf("\t\tOnFailure: abi.Failure%s,", declared.OnFailure))
	file.P("\t\tFields: []abi.Value{")
	for _, value := range values {
		file.P("\t\t\t" + value + ",")
	}
	file.P("\t\t},")
	file.P("\t}")
	if declared.Cancellable {
		file.P("\treturn b.EmitCancellable(event)")
	} else {
		file.P("\tb.EmitObservational(event)")
	}
	file.P("}")
	file.P()
	return nil
}

// actorOr names the player a permission map is resolved against. An event with
// no player resolves against none, and every node reads as false — which is
// correct: there is nobody to hold one.
func actorOr(actor string) string {
	if actor == "" {
		return "nil"
	}
	return actor
}

func describe(declared event) string {
	if declared.Observational {
		return "Observational, never cancelled"
	}
	if declared.Cancellable {
		return "Cancellable, blocks the tick, defaults to " + strings.ToLower(declared.OnFailure)
	}
	return "Blocks the tick"
}

func lowerFirst(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}

// reservedGoNames are the packages the generated file imports. A parameter
// taking one of these names still compiles — the type in the signature is
// resolved before the parameter is in scope — but it shadows the package inside
// the body, which is exactly the kind of thing that reads as correct until
// somebody adds a line that needs the package.
var reservedGoNames = map[string]struct{}{
	"abi": {}, "player": {}, "spatial": {}, "coreworld": {},
}

func parameterName(f field) string {
	name := lowerFirst(f.GoName())
	if _, reserved := reservedGoNames[name]; reserved {
		return name + "Ref"
	}
	return name
}
