// Command genpumpkincreative converts Pumpkin's Bedrock creative JSON into a
// compact Go catalogue. Unlike Pumpkin's current generated Rust table, GoCraft
// retains the NBT variants and block network IDs present in the authoritative
// Bedrock JSON. The client needs those distinctions when it builds its Creative
// search index (enchanted books alone have more than a hundred NBT variants).
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"

	"github.com/sandertv/gophertunnel/minecraft/nbt"
)

type source struct {
	Groups []struct {
		Name     string `json:"name"`
		Category string `json:"category"`
		Icon     struct {
			ID     string `json:"id"`
			Damage int16  `json:"damage"`
		} `json:"icon"`
	} `json:"groups"`
	Items []struct {
		ID            string `json:"id"`
		Damage        int16  `json:"damage"`
		GroupID       uint32 `json:"groupId"`
		NBTBase64     string `json:"nbt_b64"`
		BlockStateB64 string `json:"block_state_b64"`
	} `json:"items"`
}

type runtimeItemState struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func main() {
	input := flag.String("input", "", "Pumpkin assets/bedrock/creative_items.json")
	runtimeItems := flag.String("runtime-items", "", "Pumpkin assets/bedrock/runtime_item_states.json")
	output := flag.String("output", "bedrock/creative_catalog_generated.go", "generated Go file")
	flag.Parse()
	if *input == "" || *runtimeItems == "" {
		panic("-input and -runtime-items are required")
	}
	raw, err := os.ReadFile(*input)
	if err != nil {
		panic(err)
	}
	var data source
	if err := json.Unmarshal(raw, &data); err != nil {
		panic(err)
	}
	runtimeRaw, err := os.ReadFile(*runtimeItems)
	if err != nil {
		panic(err)
	}
	var runtimeStates []runtimeItemState
	if err := json.Unmarshal(runtimeRaw, &runtimeStates); err != nil {
		panic(err)
	}
	runtimeIDs := make(map[string]int32, len(runtimeStates))
	for _, state := range runtimeStates {
		runtimeIDs[state.Name] = state.ID
	}
	for index, item := range data.Items {
		if item.GroupID >= uint32(len(data.Groups)) {
			panic(fmt.Sprintf("item %d (%s) has invalid group %d", index, item.ID, item.GroupID))
		}
		if _, ok := runtimeIDs[item.ID]; !ok {
			panic(fmt.Sprintf("item %d (%s) has no runtime ID", index, item.ID))
		}
	}

	category := map[string]int32{"construction": 1, "nature": 2, "equipment": 3, "items": 4, "commands": 5}
	var out bytes.Buffer
	out.WriteString("// Code generated by genpumpkincreative; DO NOT EDIT.\n\npackage bedrock\n\n")
	out.WriteString("type pumpkinCreativeGroupData struct {\n\tcategory int32\n\tname string\n\ticonName string\n\ticonMeta int16\n\ticonRuntimeID int32\n}\n\n")
	out.WriteString("type pumpkinCreativeItemData struct {\n\tname string\n\tmeta int16\n\tgroup uint32\n\truntimeID int32\n\tnbtBase64 string\n\tblockRuntimeID int32\n}\n\n")
	out.WriteString("var pumpkinCreativeGroups = []pumpkinCreativeGroupData{\n")
	for _, group := range data.Groups {
		cat, ok := category[group.Category]
		if !ok {
			cat = 6
		}
		iconRuntimeID := int32(0)
		if group.Icon.ID != "" {
			var found bool
			iconRuntimeID, found = runtimeIDs[group.Icon.ID]
			if !found {
				panic(fmt.Sprintf("creative group %q icon %s has no runtime ID", group.Name, group.Icon.ID))
			}
		}
		fmt.Fprintf(&out, "\t{category: %d, name: %s, iconName: %s, iconMeta: %d, iconRuntimeID: %d},\n",
			cat, strconv.Quote(group.Name), strconv.Quote(group.Icon.ID), group.Icon.Damage, iconRuntimeID)
	}
	out.WriteString("}\n\nvar pumpkinCreativeItems = []pumpkinCreativeItemData{\n")
	for _, item := range data.Items {
		blockRuntimeID := decodeBlockRuntimeID(item.BlockStateB64)
		fmt.Fprintf(&out, "\t{name: %s, meta: %d, group: %d, runtimeID: %d, nbtBase64: %s, blockRuntimeID: %d},\n",
			strconv.Quote(item.ID), item.Damage, item.GroupID, runtimeIDs[item.ID], strconv.Quote(item.NBTBase64), blockRuntimeID)
	}
	out.WriteString("}\n")
	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		panic(err)
	}
}

func decodeBlockRuntimeID(encoded string) int32 {
	if encoded == "" {
		return 0
	}
	raw, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		panic(fmt.Errorf("decode creative block state: %w", err))
	}
	var state map[string]any
	if err := nbt.UnmarshalEncoding(raw, &state, nbt.LittleEndian); err != nil {
		panic(fmt.Errorf("decode creative block state NBT: %w", err))
	}
	networkID, ok := state["network_id"].(int32)
	if !ok {
		panic(fmt.Sprintf("creative block state network_id is %T, want int32", state["network_id"]))
	}
	return networkID
}
